---
- name: Install System Tools
  hosts: all
  become: true
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install htop, bpytop, neofetch, tree, and nload packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - htop
        - bpytop
        - neofetch
        - tree
        - nload
        - nano
        - curl
        - git

  handlers:
    - name: Notify Success
      uri:
        url: "https://gf.lrdjx.nl/message?token=A4dy7WXIAESxtLa"
        method: POST
        body: "title=Ansible%20Playbook%20Success&message=All%20specified%20packages%20were%20installed%20successfully."

    - name: Notify Failure
      uri:
        url: "https://gf.lrdjx.nl/message?token=A4dy7WXIAESxtLa"
        method: POST
        body: "title=Ansible%20Playbook%20Failure&message=Something%20went%20wrong%20during%20the%20installation%20of%20specified%20packages.%20Please%20check%20the%20logs."
      when: ansible_failed_result | bool or ansible_play_batch | skipped | bool