---
- name: Install System some System Tools
  hosts: all
  become: true
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install System Tools
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - htop
        - bpytop
        - neofetch
        - tree
        - nload
        - nano
        - curl
        - git